"use client";

import Link from "next/link";
import { WorkspaceBreadcrumbs } from "@/components/workspace-breadcrumbs";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { apiDownload, apiRequest, formatBytes } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import type { ConfirmedFile, DocumentsUploadResponse, RegistryUploadResponse, UploadSlot } from "@/lib/types";

type UploadState = { name: string; size: number; progress: number; status: "waiting" | "uploading" | "done" | "error"; message?: string };
const MAX_FILE = 50 * 1024 * 1024; const MAX_BATCH = 200 * 1024 * 1024; const ALLOWED = [".pdf", ".docx", ".xml"];
function uploadSlot(slot: UploadSlot, file: File, onProgress: (value: number) => void): Promise<void> {
  return new Promise((resolve, reject) => {
    const body = new FormData(); Object.entries(slot.upload_fields).forEach(([key, value]) => body.append(key, value)); body.append("file", file);
    const xhr = new XMLHttpRequest(); xhr.open("POST", slot.upload_url); xhr.upload.onprogress = (event) => { if (event.lengthComputable) onProgress(Math.round(event.loaded / event.total * 100)); }; xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error("Хранилище отклонило файл (" + xhr.status + ").")); xhr.onerror = () => reject(new Error("Не удалось передать файл в хранилище.")); xhr.ontimeout = () => reject(new Error("Истекло время ожидания загрузки.")); xhr.timeout = 10 * 60 * 1000; xhr.send(body);
  });
}
function saveBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
function FileGlyph() { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M13 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10z"/><path d="M13 3v7h7M8 15h8M8 18h5"/></svg>; }
const stepLabels = ["Файлы", "Загрузка", "Проверка", "Реестр"];

export default function NewCheckPage() {
  const params = useParams<{ objectId: string }>(); const objectId = params.objectId; const { token } = useAuth(); const router = useRouter(); const searchParams = useSearchParams(); const picker = useRef<HTMLInputElement>(null);
  const [files, setFiles] = useState<File[]>([]); const [invalid, setInvalid] = useState<string[]>([]); const [step, setStep] = useState(0); const [processId, setProcessId] = useState(""); const [uploads, setUploads] = useState<UploadState[]>([]); const [confirmed, setConfirmed] = useState<ConfirmedFile[]>([]); const [fileNamesById, setFileNamesById] = useState<Record<string, string>>({}); const [registry, setRegistry] = useState<File | null>(null); const [registryResult, setRegistryResult] = useState<RegistryUploadResponse | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [templateBusy, setTemplateBusy] = useState(false); const registryPicker = useRef<HTMLInputElement>(null);
  const totalSize = useMemo(() => files.reduce((sum, file) => sum + file.size, 0), [files]);
  useEffect(() => {
    const existingProcessId = searchParams.get("processId");
    if (!token || !existingProcessId || processId) return;
    setProcessId(existingProcessId);
    setStep(3);
  }, [processId, searchParams, token]);
  function pickFiles(list: FileList | null) { if (!list) return; const chosen = Array.from(list); const issues: string[] = []; const accepted: File[] = []; let currentTotal = totalSize; for (const file of chosen) { const ext = file.name.slice(file.name.lastIndexOf(".")).toLowerCase(); if (!ALLOWED.includes(ext)) { issues.push(file.name + " — неподдерживаемый формат"); continue; } if (file.size > MAX_FILE) { issues.push(file.name + " — превышен лимит 50 МБ"); continue; } if (currentTotal + file.size > MAX_BATCH) { issues.push(file.name + " — общий объем превысит 200 МБ"); continue; } if (files.some((existing) => existing.name === file.name && existing.size === file.size) || accepted.some((existing) => existing.name === file.name && existing.size === file.size)) { issues.push(file.name + " — такой файл уже выбран"); continue; } accepted.push(file); currentTotal += file.size; } setFiles((current) => current.concat(accepted)); setInvalid(issues); setError(""); }
  function removeFile(file: File) { setFiles((current) => current.filter((item) => item !== file)); }
  async function sendFiles() {
    if (!token || !files.length) return; const batchFiles = uploads.some((item) => item.status === "error") ? files.filter((file) => uploads.some((entry) => entry.name === file.name && entry.status === "error")) : files; setBusy(true); setError("");
    try {
      const request = await apiRequest<DocumentsUploadResponse>("/documents/upload", token, { method: "POST", body: JSON.stringify({ object_id: objectId, process_id: processId || undefined, files: batchFiles.map((file) => ({ original_name: file.name, size_bytes: file.size })) }) });
      setProcessId(request.process_id); setStep(1);
      const statuses: UploadState[] = batchFiles.map((file) => ({ name: file.name, size: file.size, progress: 0, status: "waiting" })); setUploads(statuses);
      let failed = false;
      for (let index = 0; index < request.files.length; index++) {
        const slot = request.files[index]; const file = batchFiles.find((item) => item.name === slot.original_name);
        if (!file) { failed = true; statuses[index] = { ...statuses[index], status: "error", message: "Не удалось сопоставить выбранный файл." }; continue; }
        statuses[index] = { ...statuses[index], status: "uploading" }; setUploads([...statuses]);
        try { await uploadSlot(slot, file, (progress) => { statuses[index] = { ...statuses[index], progress }; setUploads([...statuses]); }); statuses[index] = { ...statuses[index], progress: 100, status: "done" }; }
        catch (err) { failed = true; statuses[index] = { ...statuses[index], status: "error", message: err instanceof Error ? err.message : "Ошибка загрузки." }; }
        setUploads([...statuses]);
      }
      if (failed) { setError("Некоторые файлы не загрузились. Нажмите «Повторить отправку» — остальные документы сохранятся."); setBusy(false); return; }
      setFileNamesById((current) => ({ ...current, ...Object.fromEntries(request.files.map((slot) => [slot.file_id, slot.original_name])) }));
      const check = await apiRequest<{ files: ConfirmedFile[] }>("/documents/" + request.process_id + "/confirm", token, { method: "POST" }); setConfirmed(check.files || []); setStep(2);
    } catch (err) { setError(err instanceof Error ? err.message : "Не удалось загрузить документы."); }
    finally { setBusy(false); }
  }
  async function downloadTemplate() { if (!token) return; setTemplateBusy(true); setError(""); try { const blob = await apiDownload("/documents/" + processId + "/registry-template?format=xlsx", token); saveBlob(blob, "Реестр_документов_объекта.xlsx"); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось скачать шаблон."); } finally { setTemplateBusy(false); } }
  async function submitRegistry() { if (!token || !registry || !processId) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", registry); const result = await apiRequest<RegistryUploadResponse>("/documents/" + processId + "/registry", token, { method: "POST", body }); setRegistryResult(result); setStep(3); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось обработать реестр."); } finally { setBusy(false); } }
  const acceptedCount = confirmed.filter((item) => item.check_status === "ACCEPTED").length;
  const goToCheck = () => router.push("/checks/" + processId);
  return <>
    <WorkspaceBreadcrumbs objectId={objectId} current="Новая проверка"/>
    <div className="page-head"><div><div className="page-eyebrow">ПОДГОТОВКА ПРОВЕРКИ</div><h1 className="page-title">Загрузка документов</h1><p className="page-subtitle">Загрузите комплект, проверьте файлы и свяжите их с реестром.</p></div><span className="flow-context"><span className="flow-dot"/> Объект выбран</span></div>
    <div className="wizard-steps">{stepLabels.map((label, index) => <div className={"wizard-step " + (index === step ? "current" : index < step ? "complete" : "")} key={label}><span className="wizard-num">{index < step ? "✓" : "0" + (index + 1)}</span><span>{label}</span>{index < stepLabels.length - 1 && <i/>}</div>)}</div>
    {error && <div className="alert alert-error wizard-alert"><span>!</span><div>{error}</div></div>}
    {step === 0 && <section className="surface wizard-card">
      <div className="wizard-card-head"><div><h2>Выберите документы</h2><p>Файлы проектной, рабочей и исполнительной документации.</p></div><span className="step-count">ШАГ 01 / 04</span></div>
      <div className="drop-zone" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); pickFiles(event.dataTransfer.files); }}><span className="drop-icon"><FileGlyph/></span><strong>Перетащите файлы сюда</strong><span>или</span><button className="button button-secondary" type="button" onClick={() => picker.current?.click()}>Выбрать файлы</button><small>PDF, DOCX, XML · не более 50 МБ на файл · до 200 МБ всего</small><input ref={picker} type="file" accept=".pdf,.docx,.xml" multiple hidden onChange={(event: ChangeEvent<HTMLInputElement>) => { pickFiles(event.target.files); event.target.value = ""; }}/></div>
      {invalid.length > 0 && <div className="alert alert-warning file-issues"><span>△</span><div>{invalid.map((message) => <div key={message}>{message}</div>)}</div></div>}
      {files.length > 0 && <div className="selected-files"><div className="file-list-heading"><strong>Выбрано файлов <b>{files.length}</b></strong><span>{formatBytes(totalSize)} из 200 МБ</span></div>{files.map((file) => <div className="selected-file" key={file.name + file.size}><span className="file-type-icon"><FileGlyph/></span><span className="file-name"><strong>{file.name}</strong><small>{formatBytes(file.size)}</small></span><button className="remove-file" onClick={() => removeFile(file)} aria-label={"Убрать " + file.name}>×</button></div>)}</div>}
      <div className="wizard-actions"><Link href={"/objects/" + objectId} className="button button-quiet">Отмена</Link><button className="button button-primary" disabled={!files.length || busy} onClick={sendFiles}>Загрузить и продолжить <span>→</span></button></div>
    </section>}
    {step === 1 && <section className="surface wizard-card"><div className="wizard-card-head"><div><h2>{uploads.some((item) => item.status === "error") ? "Повторная отправка" : "Передаем документы"}</h2><p>Каждый файл отправляется в защищенное хранилище и затем проходит проверку.</p></div><span className="step-count">ШАГ 02 / 04</span></div><div className="upload-queue">{uploads.map((item) => <div className="upload-row" key={item.name}><span className={"upload-file-icon " + (item.status === "error" ? "is-error" : item.status === "done" ? "is-done" : "")}><FileGlyph/></span><span className="file-name"><strong>{item.name}</strong><small>{item.status === "error" ? item.message : item.status === "done" ? "Загружен · " + formatBytes(item.size) : item.status === "uploading" ? "Загружается · " + item.progress + "%" : formatBytes(item.size)}</small>{item.status !== "error" && <i className="upload-progress"><b style={{ width: item.progress + "%" }}/></i>}</span><span className="upload-state">{item.status === "done" ? "✓" : item.status === "error" ? "!" : item.status === "uploading" ? <span className="spinner"/> : "·"}</span></div>)}</div><div className="wizard-actions"><span className="upload-footnote">ID проверки: <code>{processId.slice(0, 8)}…</code></span>{uploads.some((item) => item.status === "error") ? <button className="button button-primary" disabled={busy} onClick={sendFiles}>{busy ? "Отправляем…" : "Повторить отправку"}</button> : <span className="loading-inline"><span className="spinner"/> Проверяем файлы…</span>}</div></section>}
    {step === 2 && <section className="surface wizard-card"><div className="wizard-card-head"><div><h2>Результат проверки</h2><p>Поврежденные и неподдерживаемые файлы не попадут в анализ.</p></div><span className="step-count">ШАГ 03 / 04</span></div><div className="check-summary"><span className="check-summary-icon">✓</span><div><strong>{acceptedCount} из {confirmed.length} {plural(acceptedCount,"файл принят","файла принято","файлов принято")}</strong><small>Результат проверки по формату, размеру и целостности.</small></div></div><div className="upload-queue">{confirmed.map((file) => <div className="upload-row" key={file.file_id}><span className={"file-check-mark " + (file.check_status === "ACCEPTED" ? "accepted" : "rejected")}>{file.check_status === "ACCEPTED" ? "✓" : "!"}</span><span className="file-name"><strong>{fileNamesById[file.file_id] || file.file_id.slice(0, 8)}</strong><small>{file.check_status === "ACCEPTED" ? (file.page_count ? file.page_count + " страниц · " : "") + "Файл готов" : file.check_error || checkStatusName(file.check_status)}</small></span><span className={"file-result-label " + (file.check_status === "ACCEPTED" ? "result-ok" : "result-bad")}>{file.check_status === "ACCEPTED" ? "Принят" : "Отклонен"}</span></div>)}</div>{acceptedCount === 0 && <div className="alert alert-error"><span>!</span>Нет принятых файлов. Вернитесь к загрузке и выберите документы в допустимом формате.</div>}<div className="wizard-actions"><Link href={"/objects/" + objectId} className="button button-quiet">Отмена</Link><button className="button button-primary" disabled={!acceptedCount} onClick={() => setStep(3)}>К реестру <span>→</span></button></div></section>}
    {step === 3 && <section className="surface wizard-card"><div className="wizard-card-head"><div><h2>Свяжите файлы с реестром</h2><p>Реестр сообщает системе, к какой стадии и редакции относится каждый файл.</p></div><span className="step-count">ШАГ 04 / 04</span></div>
      <div className="registry-explainer"><span className="registry-symbol">≋</span><div><strong>Для сравнения система должна знать стадию каждого документа</strong><p>В шаблоне уже будут заполнены имена и контрольные суммы принятых файлов. Укажите ПД, РД или ИД, шифр, редакцию и статус утверждения.</p></div></div>
      <div className="template-row"><span className="template-icon"><FileGlyph/></span><div><strong>Шаблон реестра по загруженным файлам</strong><small>XLSX · внутри есть инструкция и списки допустимых значений</small></div><button className="button button-secondary" disabled={templateBusy || !processId} onClick={downloadTemplate}>{templateBusy ? <span className="spinner"/> : "↓"} Скачать шаблон</button></div>
      <div className="registry-upload" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const file = event.dataTransfer.files[0]; if (file) setRegistry(file); }}><input type="file" accept=".xlsx,.csv,.json" hidden ref={registryPicker} onChange={(event) => setRegistry(event.target.files?.[0] || null)}/><span className="registry-upload-icon"><FileGlyph/></span><div><strong>{registry ? registry.name : "Загрузите заполненный реестр"}</strong><small>{registry ? formatBytes(registry.size) + " · готов к проверке" : "XLSX, CSV или JSON"}</small></div><button className="button button-secondary" type="button" onClick={() => registryPicker.current?.click()}>{registry ? "Заменить файл" : "Выбрать файл"}</button></div>
      <div className="alert alert-info registry-important"><span>i</span>Без реестра у системы нет надежной связи между файлом и стадией документации — сравнение не сможет дать корректный результат.</div>
      <div className="wizard-actions"><button className="button button-quiet" onClick={() => setStep(2)}>← Назад</button><button className="button button-primary" disabled={!registry || busy} onClick={submitRegistry}>{busy ? <><span className="spinner"/> Обрабатываем…</> : <>Проверить реестр <span>→</span></>}</button></div>
    </section>}
    {registryResult && step === 3 && <div className="registry-result surface"><div><span className="result-check">✓</span><strong>Реестр обработан</strong></div><div className="registry-result-counts"><span><b>{registryResult.matched}</b> сопоставлено</span><span><b>{registryResult.unmatched}</b> не найдено</span><span><b>{registryResult.invalid || 0}</b> с ошибками</span></div>{registryResult.errors?.length ? <div className="registry-errors">{registryResult.errors.slice(0, 4).map((item) => <span key={item}>{item}</span>)}</div> : null}{registryResult.warnings?.length ? <div className="alert alert-warning">{registryResult.warnings.slice(0, 3).join(" · ")}</div> : null}<div className="registry-result-bottom"><span>Можно исправить реестр и загрузить его еще раз.</span><button className="button button-primary" onClick={goToCheck}>Перейти к проверке <span>→</span></button></div></div>}
    <div className="wizard-footnote"><span>i</span> Все загруженные файлы проверяются на поддерживаемый формат, размер и целостность.</div>
  </>;
}
function checkStatusName(status: string) { const names: Record<string,string> = { REJECTED_FORMAT: "Неподдерживаемый формат", REJECTED_SIZE: "Превышен допустимый размер", REJECTED_CORRUPTED: "Файл поврежден", REJECTED_VIRUS: "Файл не прошел антивирусную проверку" }; return names[status] || status; }
function plural(value: number, one: string, few: string, many: string) { const n = Math.abs(value) % 100; const last = n % 10; if (n > 10 && n < 20) return many; if (last > 1 && last < 5) return few; if (last === 1) return one; return many; }
