"use client";

import Link from "next/link";
import { WorkspaceBreadcrumbs } from "@/components/workspace-breadcrumbs";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { apiRequest, formatDate } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import type { EvidenceFragment, Finding } from "@/lib/types";

const reasons = [["WRONG_REVISION", "Использована другая редакция"], ["APPROVED_CHANGE", "Изменение согласовано"], ["OCR_ERROR", "Ошибка распознавания документа"], ["LINKING_ERROR", "Неверная связь документов"], ["NOT_APPLICABLE", "Параметр неприменим"], ["DUPLICATE", "Повторный вывод"], ["OTHER", "Другая причина"]];
export default function FindingPage() {
  const { processId, findingId } = useParams<{ processId: string; findingId: string }>(); const { token } = useAuth(); const router = useRouter(); const [finding, setFinding] = useState<Finding | null>(null); const [links, setLinks] = useState<Record<string, string>>({}); const [decision, setDecision] = useState("CONFIRMED_VIOLATION"); const [reason, setReason] = useState(""); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!token) return; apiRequest<Finding>(`/findings/${findingId}`, token).then(async f => { setFinding(f); setDecision(f.inspector_status === "PENDING" ? "CONFIRMED_VIOLATION" : f.inspector_status); setReason(f.reason_code || ""); setComment(f.comment || ""); const entries = await Promise.all((f.evidence || []).map(async evidence => { try { const r = await apiRequest<{url:string}>(`/files/${evidence.file_id}/download-url`, token); return [evidence.file_id, r.url] as const; } catch { return [evidence.file_id, ""] as const; } })); setLinks(Object.fromEntries(entries)); }).catch(e => setError(e instanceof Error ? e.message : "Не удалось загрузить вывод.")); }, [findingId, token]);
  async function save() { if (!token || !finding) return; if (comment.trim().length < 3) { setError("Добавьте комментарий не короче 3 символов."); return; } if (decision === "NEGATIVE_VERIFIED" && !reason) { setError("Для отклонения вывода укажите причину."); return; } setBusy(true); setError(""); try { await apiRequest(`/findings/${findingId}/decision`, token, { method: "POST", body: JSON.stringify({ decision, ...(reason ? { reason_code: reason } : {}), comment: comment.trim() }) }); router.push(`/checks/${processId}/protocol`); } catch(e) { setError(e instanceof Error ? e.message : "Не удалось сохранить решение."); } finally { setBusy(false); } }
  return <>
    <WorkspaceBreadcrumbs processId={processId} processAncestor protocolAncestor current={finding?.parameter_name || "Карточка вывода"}/>
    {!finding ? <div className="surface loading-card">Загружаем вывод и доказательства…{error && <p>{error}</p>}</div> : <>
      <div className="page-head"><div><div className="page-eyebrow">{finding.param_code || "ПАРАМЕТР"} · {finding.review_priority === "HIGH" ? "ВЫСОКИЙ ПРИОРИТЕТ" : "ПРОВЕРКА ВЫВОДА"}</div><h1 className="page-title">{finding.parameter_name || "Карточка вывода"}</h1><p className="page-subtitle">Сопоставьте основание системы с документами и зафиксируйте решение.</p></div><Link className="button button-secondary" href={`/checks/${processId}/protocol`}>← К протоколу</Link></div>
      {error && <div className="alert alert-error"><span>!</span>{error}</div>}
      <div className="finding-detail-grid"><main>
        <section className="surface comparison-card"><div className="section-head"><div><h2>Сравнение значений</h2><p>{finding.rationale || "Основание автоматического вывода"}</p></div></div><div className="comparison-values"><div><small>Ожидаемое значение</small><strong>{finding.expected_value || "—"}</strong><span>Проектная документация</span></div><b>→</b><div><small>Фактическое значение</small><strong>{finding.actual_value || "—"} {finding.unit || ""}</strong><span>Рабочая или исполнительная документация</span></div></div>{finding.delta && <div className="delta-line">Разница: <strong>{finding.delta}</strong></div>}</section>
        <section className="surface evidence-panel"><div className="section-head"><div><h2>Документальные основания</h2><p>Источник, страница и фрагмент, на котором основан вывод.</p></div><span className="count-pill">{finding.evidence?.length || 0}</span></div>{finding.evidence?.length ? finding.evidence.map((ev, i) => <EvidenceCard key={ev.file_id + i} evidence={ev} url={links[ev.file_id]}/>) : <div className="empty-state">В ответе API нет привязанных фрагментов.</div>}</section>
      </main><aside className="surface decision-panel"><div className="page-eyebrow">РЕШЕНИЕ ИНСПЕКТОРА</div>{finding.finding_status !== "CANDIDATE" ? <><h2>Решение не требуется</h2><p className="decision-readonly">Для этого результата API не запрашивает решение по кандидату. Просмотрите значения и документальные основания.</p><span className="protocol-state">{finding.finding_status}</span></> : <><h2>Как трактовать вывод?</h2><label className="decision-option"><input type="radio" name="decision" value="CONFIRMED_VIOLATION" checked={decision === "CONFIRMED_VIOLATION"} onChange={e => setDecision(e.target.value)}/><span><strong>Подтвердить расхождение</strong><small>Система верно обнаружила проблему.</small></span></label><label className="decision-option"><input type="radio" name="decision" value="NEGATIVE_VERIFIED" checked={decision === "NEGATIVE_VERIFIED"} onChange={e => setDecision(e.target.value)}/><span><strong>Расхождения нет</strong><small>Вывод системы не подтверждается.</small></span></label><label className="decision-option"><input type="radio" name="decision" value="CLARIFICATION_REQUIRED" checked={decision === "CLARIFICATION_REQUIRED"} onChange={e => setDecision(e.target.value)}/><span><strong>Нужно уточнение</strong><small>Недостаточно данных для решения.</small></span></label><label className="field-label" htmlFor="reason">Причина{decision === "NEGATIVE_VERIFIED" ? <span> обязательна</span> : null}</label><select id="reason" className="field-control" value={reason} onChange={e => setReason(e.target.value)}><option value="">Выберите причину</option>{reasons.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><label className="field-label" htmlFor="comment">Комментарий <span>обязательно</span></label><textarea id="comment" className="field-control decision-comment" value={comment} onChange={e => setComment(e.target.value)} placeholder="Укажите, на что вы опирались при решении"/><small className="decision-hint">Решение и комментарий попадут в версию протокола.</small><button className="button button-primary button-wide" disabled={busy} onClick={() => void save()}>{busy ? "Сохраняем…" : "Сохранить решение"}</button>{finding.decided_at && <small className="decision-date">Последнее решение · {formatDate(finding.decided_at, true)}</small>}</>}</aside></div>
    </>}
  </>;
}
function EvidenceCard({ evidence: e, url }: { evidence: EvidenceFragment; url?: string }) { return <article className="evidence-card"><div className="evidence-card-head"><span className={`evidence-tag ${e.role}`}>{e.role === "expected" ? "ОЖИДАЕМОЕ" : "ФАКТИЧЕСКОЕ"}</span><span>{e.stage || "Стадия не указана"}{e.page ? ` · стр. ${e.page}` : ""}</span>{url && <a href={url} target="_blank" rel="noreferrer">Открыть файл ↗</a>}</div><strong>{e.original_name || "Документ"}</strong>{e.quote && <blockquote>«{e.quote}»</blockquote>}{e.extracted_value && <div className="extracted-value">Распознано: <b>{e.extracted_value}</b></div>}{e.bbox && <small className="bbox-note">Фрагмент страницы {e.page || "—"} указан системой{e.bbox[0] === 0 && e.bbox[1] === 0 && e.bbox[2] === 1 && e.bbox[3] === 1 ? "; точная область не определена" : "."}</small>}</article>; }
